// <auto-generated />
using ApiTest;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTest.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241013183716_PostgreSQL-inicial")]
    partial class PostgreSQLinicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiTest.DetalleVenta", b =>
                {
                    b.Property<int>("Id_Det")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Det"));

                    b.Property<int>("Id_Pro")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Ven")
                        .HasColumnType("integer");

                    b.Property<int[]>("Productos")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id_Det");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("ApiTest.Producto", b =>
                {
                    b.Property<int>("Id_Pro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pro"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumSerie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id_Pro");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ApiTest.Venta", b =>
                {
                    b.Property<int>("Id_Ven")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Ven"));

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id_Ven");

                    b.ToTable("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
